"""change_is_active_to_boolean

Revision ID: 672ff6277783
Revises: 478ba368796f
Create Date: 2026-04-01 10:16:08.662195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672ff6277783'
down_revision = '478ba368796f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, convert string values to proper boolean representation
    op.execute("""
        UPDATE accounts 
        SET is_active = CASE 
            WHEN is_active IN ('True', 'true', 't', '1', 'yes') THEN 'true'
            WHEN is_active IN ('False', 'false', 'f', '0', 'no') THEN 'false'
            ELSE 'true'
        END
    """)
    
    # Now alter the column type with explicit casting
    op.alter_column('accounts', 'is_active',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='is_active::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
