"""Add to_account_id for internal transfers

Revision ID: 6a435ab14ce1
Revises: 672ff6277783
Create Date: 2026-04-03 00:39:51.535076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a435ab14ce1'
down_revision = '672ff6277783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_to_account_id'), 'transactions', ['to_account_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_to_account_id'), table_name='transactions')
    op.drop_column('transactions', 'to_account_id')
    # ### end Alembic commands ###
