"""add_insights_and_ai_interactions_tables

Revision ID: c33b226187eb
Revises: 7b8c9d0e1f2a
Create Date: 2026-04-03 09:17:23.897266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33b226187eb'
down_revision = '7b8c9d0e1f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
